import { z } from "zod";

// API schemas (the single source of truth for both validation and the
// generated OpenAPI document).

export const TreatmentInputSchema = z.object({
  name: z.string().min(1).max(80),
  factors: z.record(z.unknown()),
  description: z.string().optional(),
});

export const BatchSlotSchema = z.object({
  treatmentId: z.string().min(1),
  count: z.number().int().positive(),
});

export const CreateBatchSchema = z.object({
  name: z.string().optional(),
  slots: z.array(BatchSlotSchema).min(1),
  lobbyConfig: z
    .object({
      kind: z.enum(["shared", "individual"]),
      durationMs: z.number().int().positive(),
      strategy: z.enum(["fail", "ignore"]).default("fail"),
    })
    .optional(),
});
export type CreateBatchBody = z.infer<typeof CreateBatchSchema>;

export const CreateParticipantSchema = z.object({
  identifier: z.string().min(1).max(200),
  metadata: z.record(z.unknown()).optional(),
  /** Optional batch scope; the issued token will be valid only for this batch. */
  batchId: z.string().optional(),
  /** Token TTL in ms. Defaults to 6 hours. */
  ttlMs: z.number().int().positive().optional(),
});

export const SetStateSchema = z.object({
  scope: z.enum(["player", "playerStage", "playerRound", "game"]),
  scopeId: z.string().min(1),
  key: z.string().min(1),
  value: z.unknown(),
  immutable: z.boolean().optional(),
  private: z.boolean().optional(),
});

export const DevLoginSchema = z.object({
  username: z.string().min(1),
  password: z.string().min(1),
});

// OpenAPI document — generated by hand for now to avoid a heavy zod-to-openapi
// dependency at this early stage. We'll keep it in sync with the schemas
// above. Tests assert the document references real endpoints.
export function openapiDocument(): Record<string, unknown> {
  return {
    openapi: "3.1.0",
    info: {
      title: "Empirica API",
      version: "0.0.0",
      description: "REST API for Empirica v3.",
    },
    paths: {
      "/health": {
        get: {
          summary: "Health check",
          responses: { "200": { description: "ok" } },
        },
      },
      "/api/auth/dev": {
        post: {
          summary: "Dev provider login",
          responses: {
            "200": { description: "JWT" },
            "401": { description: "Unauthorized" },
          },
        },
      },
      "/api/admin/batches": {
        get: { summary: "List batches", responses: { "200": { description: "ok" } } },
        post: {
          summary: "Create batch",
          responses: { "201": { description: "Created" } },
        },
      },
      "/api/admin/batches/{id}": {
        get: { summary: "Get batch", responses: { "200": { description: "ok" } } },
      },
      "/api/admin/batches/{id}/start": {
        post: { summary: "Start batch", responses: { "200": { description: "ok" } } },
      },
      "/api/admin/batches/{id}/end": {
        post: { summary: "End batch", responses: { "200": { description: "ok" } } },
      },
      "/api/admin/games/{id}": {
        get: { summary: "Get game", responses: { "200": { description: "ok" } } },
      },
      "/api/admin/games/{id}/start": {
        post: { summary: "Start game", responses: { "200": { description: "ok" } } },
      },
      "/api/admin/games/{id}/end": {
        post: { summary: "End game", responses: { "200": { description: "ok" } } },
      },
      "/api/admin/treatments": {
        get: { summary: "List treatments", responses: { "200": { description: "ok" } } },
        post: { summary: "Create treatment", responses: { "201": { description: "Created" } } },
      },
      "/api/admin/participants": {
        post: {
          summary: "Create or refresh participant + token",
          responses: { "200": { description: "ok" } },
        },
      },
      "/api/me": {
        get: { summary: "Current player view", responses: { "200": { description: "ok" } } },
      },
      "/api/me/state": {
        post: { summary: "Set state on current player", responses: { "200": { description: "ok" } } },
      },
    },
  };
}
