name: ⭐ Feature
description: Request a Feature
# title: ""
labels: ["enhancement"]
# assignees:
#   - npaton
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: |
        Please search to see if an issue already exists for the
        feature you're requesting.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I have an issue when...
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen. Add any considered drawbacks..
      placeholder: I would like...
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: We could have...
    validations:
      required: false
  - type: textarea
    id: adoption
    attributes:
      label: Teachability, Documentation, Adoption, Migration Strategy
      description: |
        If you can, explain how users will be able to use this and
        possibly write out a version of the docs. Maybe a screenshot or design?

        Tip: You can attach images or log files by clicking this area to
        highlight it and then dragging files in.
      placeholder: User would...
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/empiricaly/empirica/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
